on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, windows-2019, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: install cairo
        run: brew install cairo
        if: contains(matrix.os, 'mac')

      - name: install libgtk-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev
        if: contains(matrix.os, 'ubuntu')

      - name: restore cache
        uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
